version: '3'
services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=1234
      - DB_NAME=education
    depends_on:
      - db
  
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=education
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 